"""
Django settings for core_abnk project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zo643%xw8a@c9wn26j(ubh!rc&$8$43b2fltqonz71hou@(5#('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_abnk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_abnk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CERT_VERIFY = False

MYINFO_DOMAIN = "https://test.api.myinfo.gov.sg"
MYINFO_CLIENT_ID = "STG-202327956K-ABNK-BNPLAPPLN"

# https://public.cloud.myinfo.gov.sg/myinfo/api/myinfo-kyc-v4.0.html#section/Authentication/OAuth2
MYINFO_SCOPE = (
    # Personal
    "uinfin name sex race dob residentialstatus nationality birthcountry "
    "passtype passstatus passexpirydate "
    "employmentsector mobileno email regadd housingtype hdbtype "
    # --- Finance
    "cpfcontributions "
    "noahistory "  # Notice of Assessment (Detailed, Last 2 Years)
    "ownerprivate "  # Ownership of Private Residential Property
    # --- Education & employment
    "employment "  # Name of Employer
    "occupation "
    "cpfemployers "  # Employers as stated in CPF Contribution History (up to 15 months)
    # --- Family
    "marital"
)

# =============== MYINFO API v4 ===============
MYINFO_JWKS_TOKEN_VERIFICATION_URL = "https://test.authorise.singpass.gov.sg/.well-known/keys.json"
MYINFO_JWKS_DATA_VERIFICATION_URL = "https://test.myinfo.singpass.gov.sg/.well-known/keys.json"
MYINFO_PURPOSE_ID = os.environ.get("MYINFO_PURPOSE_ID", "7ed6f2ce")
# ansible vault somehow replaces double quotes with single quotes.
# so we need to revert to double quotes.
MYINFO_PRIVATE_KEY_SIG = os.environ.get(
    "MYINFO_PRIVATE_KEY_SIG",
    '{"alg":"ES256","crv":"P-256","d":"Y7y4AtZ_j_4FNS0tRNYKySgdx-QcBQtjQzf1NRTHDCI","kty":"EC","use":"sig","x":"k-K2AGmjySAjxPhHLA_vCv8aa-oIoACSWhyZEQmRewc","y":"WMro28Kf4Y5Y5fiwOL-WRAo9AYFBhv8GNbtr-xnz4a0"}',  # noqa: E501
).replace("'", '"')

MYINFO_PRIVATE_KEY_ENC = os.environ.get(
    "MYINFO_PRIVATE_KEY_ENC",
    '{"alg":"ECDH-ES+A256KW","crv":"P-256","d":"fqyHyvArMu7NTc_G354VCHYqDUv0WgL8TNGg5IBpaUU","kty":"EC","use":"enc","x":"AsflFcp_M8WQxWbxImCAtJ0zWf4yHYz_3jU4faD5ODg","y":"Nc8-inmbKEOyS6VGKoZDPc2mFhugrx27lcVis9E_jWs"}',  # noqa: E501
).replace("'", '"')

# ============== /MYINFO API v4 ===============
